[package]
name = "rdb-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
bstr = { version = "1.11.0", features = ["alloc"] }
byteorder = "1.5.0"
hex-literal = "0.4.1"
winnow = { version = "0.6.20", features = ["debug"] }
